-- ============================================================
-- FAST AND SAFE
-- Bodega de datos OLAP - PostgreSQL
-- ============================================================

-- Permite volver a ejecutar el archivo durante el desarrollo.
DROP TABLE IF EXISTS ft_novedad_servicio;
DROP TABLE IF EXISTS ft_fase_servicio;
DROP TABLE IF EXISTS ft_servicio;

DROP TABLE IF EXISTS dim_tipo_novedad;
DROP TABLE IF EXISTS dim_fase;
DROP TABLE IF EXISTS dim_mensajero;
DROP TABLE IF EXISTS dim_sede;
DROP TABLE IF EXISTS dim_cliente;
DROP TABLE IF EXISTS dim_hora;
DROP TABLE IF EXISTS dim_fecha;


-- ============================================================
-- DIMENSIONES
-- ============================================================

CREATE TABLE dim_fecha (
    sk_fecha        INT PRIMARY KEY,
    fecha           DATE NOT NULL UNIQUE,
    dia             SMALLINT NOT NULL,
    dia_semana      VARCHAR(15) NOT NULL,
    dia_semana_num  SMALLINT NOT NULL,
    mes             SMALLINT NOT NULL,
    mes_nombre      VARCHAR(15) NOT NULL,
    trimestre       SMALLINT NOT NULL,
    anio            SMALLINT NOT NULL,
    es_festivo      BOOLEAN NOT NULL DEFAULT FALSE,

    CHECK (dia BETWEEN 1 AND 31),
    CHECK (dia_semana_num BETWEEN 1 AND 7),
    CHECK (mes BETWEEN 1 AND 12),
    CHECK (trimestre BETWEEN 1 AND 4)
);


CREATE TABLE dim_hora (
    id_hora         SMALLINT PRIMARY KEY,
    hora_24         SMALLINT NOT NULL UNIQUE,
    franja_horaria VARCHAR(20) NOT NULL,

    CHECK (hora_24 BETWEEN 0 AND 23)
);


CREATE TABLE dim_cliente (
    sk_cliente      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente_nk   VARCHAR(50) NOT NULL UNIQUE,
    nom_cliente     VARCHAR(150) NOT NULL
);


CREATE TABLE dim_sede (
    sk_sede         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede_nk      VARCHAR(50) NOT NULL UNIQUE,
    sk_cliente      INT NOT NULL,
    nom_sede        VARCHAR(150) NOT NULL,
    ciudad          VARCHAR(100),
    direccion       VARCHAR(250),

    CONSTRAINT fk_sede_cliente
        FOREIGN KEY (sk_cliente)
        REFERENCES dim_cliente(sk_cliente)
);


CREATE TABLE dim_mensajero (
    sk_mensajero       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mensajero_nk    VARCHAR(50) NOT NULL UNIQUE,
    nom_mensajero      VARCHAR(150) NOT NULL
);


CREATE TABLE dim_fase (
    sk_fase         SMALLINT PRIMARY KEY,
    id_fase_nk      INT NOT NULL UNIQUE,
    nom_fase        VARCHAR(80) NOT NULL
);


CREATE TABLE dim_tipo_novedad (
    sk_tipo_novedad     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_novedad_nk  VARCHAR(50) NOT NULL UNIQUE,
    nom_tipo_novedad    VARCHAR(150) NOT NULL
);


-- ============================================================
-- TABLAS DE HECHOS
-- ============================================================

-- Una fila representa un servicio completo.
CREATE TABLE ft_servicio (
    id_servicio             BIGINT PRIMARY KEY,

    sk_fecha_solicitud      INT NOT NULL,
    id_hora_solicitud       SMALLINT NOT NULL,
    sk_cliente              INT NOT NULL,
    sk_sede                 INT NOT NULL,
    sk_mensajero            INT NOT NULL,

    fecha_hora_solicitud    TIMESTAMP NOT NULL,
    fecha_hora_cierre       TIMESTAMP,

    tiempo_entrega_min      NUMERIC(12,2),
    cantidad_servicios      SMALLINT NOT NULL DEFAULT 1,

    CONSTRAINT fk_servicio_fecha
        FOREIGN KEY (sk_fecha_solicitud)
        REFERENCES dim_fecha(sk_fecha),

    CONSTRAINT fk_servicio_hora
        FOREIGN KEY (id_hora_solicitud)
        REFERENCES dim_hora(id_hora),

    CONSTRAINT fk_servicio_cliente
        FOREIGN KEY (sk_cliente)
        REFERENCES dim_cliente(sk_cliente),

    CONSTRAINT fk_servicio_sede
        FOREIGN KEY (sk_sede)
        REFERENCES dim_sede(sk_sede),

    CONSTRAINT fk_servicio_mensajero
        FOREIGN KEY (sk_mensajero)
        REFERENCES dim_mensajero(sk_mensajero),

    CHECK (cantidad_servicios = 1),

    CHECK (
        tiempo_entrega_min IS NULL
        OR tiempo_entrega_min >= 0
    ),

    CHECK (
        fecha_hora_cierre IS NULL
        OR fecha_hora_cierre >= fecha_hora_solicitud
    )
);


-- Una fila representa una fase de un servicio.
CREATE TABLE ft_fase_servicio (
    id_fase_servicio      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    id_servicio           BIGINT NOT NULL,
    sk_fase               SMALLINT NOT NULL,

    fecha_hora_inicio     TIMESTAMP NOT NULL,
    fecha_hora_fin        TIMESTAMP,
    duracion_fase_min     NUMERIC(12,2),

    CONSTRAINT fk_fase_servicio
        FOREIGN KEY (id_servicio)
        REFERENCES ft_servicio(id_servicio)
        ON DELETE CASCADE,

    CONSTRAINT fk_fase_dimension
        FOREIGN KEY (sk_fase)
        REFERENCES dim_fase(sk_fase),

    CONSTRAINT uq_servicio_fase
        UNIQUE (id_servicio, sk_fase),

    CHECK (
        duracion_fase_min IS NULL
        OR duracion_fase_min >= 0
    ),

    CHECK (
        fecha_hora_fin IS NULL
        OR fecha_hora_fin >= fecha_hora_inicio
    )
);


-- Una fila representa una novedad real registrada.
CREATE TABLE ft_novedad_servicio (
    id_novedad_evento     BIGINT PRIMARY KEY,

    id_servicio           BIGINT NOT NULL,
    sk_tipo_novedad       INT NOT NULL,

    fecha_hora_novedad    TIMESTAMP,
    descripcion           VARCHAR(500),
    cantidad_novedades    SMALLINT NOT NULL DEFAULT 1,

    CONSTRAINT fk_novedad_servicio
        FOREIGN KEY (id_servicio)
        REFERENCES ft_servicio(id_servicio)
        ON DELETE CASCADE,

    CONSTRAINT fk_novedad_tipo
        FOREIGN KEY (sk_tipo_novedad)
        REFERENCES dim_tipo_novedad(sk_tipo_novedad),

    CHECK (cantidad_novedades = 1)
);


-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX idx_servicio_fecha
    ON ft_servicio(sk_fecha_solicitud);

CREATE INDEX idx_servicio_cliente
    ON ft_servicio(sk_cliente);

CREATE INDEX idx_servicio_sede
    ON ft_servicio(sk_sede);

CREATE INDEX idx_servicio_mensajero
    ON ft_servicio(sk_mensajero);

CREATE INDEX idx_fase_sk
    ON ft_fase_servicio(sk_fase);

CREATE INDEX idx_novedad_tipo
    ON ft_novedad_servicio(sk_tipo_novedad);


-- ============================================================
-- REGISTROS DESCONOCIDOS
-- Se usan cuando un dato no se encuentra en la OLTP.
-- ============================================================

INSERT INTO dim_cliente
    (sk_cliente, id_cliente_nk, nom_cliente)
VALUES
    (0, 'DESCONOCIDO', 'Cliente desconocido');


INSERT INTO dim_sede
    (sk_sede, id_sede_nk, sk_cliente, nom_sede, ciudad, direccion)
VALUES
    (0, 'DESCONOCIDA', 0, 'Sede desconocida', NULL, NULL);


INSERT INTO dim_mensajero
    (sk_mensajero, id_mensajero_nk, nom_mensajero)
VALUES
    (0, 'DESCONOCIDO', 'Mensajero desconocido');


INSERT INTO dim_tipo_novedad
    (sk_tipo_novedad, id_tipo_novedad_nk, nom_tipo_novedad)
VALUES
    (0, 'DESCONOCIDA', 'Novedad desconocida');


-- ============================================================
-- DIMENSIÓN HORA
-- ============================================================

INSERT INTO dim_hora (id_hora, hora_24, franja_horaria)
SELECT
    hora,
    hora,
    CASE
        WHEN hora BETWEEN 0 AND 5  THEN 'Madrugada'
        WHEN hora BETWEEN 6 AND 11 THEN 'Mañana'
        WHEN hora BETWEEN 12 AND 17 THEN 'Tarde'
        ELSE 'Noche'
    END
FROM generate_series(0, 23) AS hora;


-- ============================================================
-- DIMENSIÓN FASE
-- Los códigos 1, 2, 4, 5 y 6 corresponden al mapeo de la OLTP.
-- ============================================================

INSERT INTO dim_fase
    (sk_fase, id_fase_nk, nom_fase)
VALUES
    (1, 1, 'Iniciado'),
    (2, 2, 'Con mensajero asignado'),
    (3, 4, 'Recogido en origen'),
    (4, 5, 'Entregado en destino'),
    (5, 6, 'Cerrado');